// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProducerFilm.Infrastructure.Data;

#nullable disable

namespace ProducerFilm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104160725_AddMovieListHistory")]
    partial class AddMovieListHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ProducerFilm.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 4, 16, 7, 25, 522, DateTimeKind.Utc).AddTicks(5368),
                            Director = "Francis Ford Coppola",
                            Genre = "Drama",
                            Title = "O Poderoso Chefão",
                            Year = 1972
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 4, 16, 7, 25, 522, DateTimeKind.Utc).AddTicks(5370),
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            Title = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 4, 16, 7, 25, 522, DateTimeKind.Utc).AddTicks(5371),
                            Director = "Christopher Nolan",
                            Genre = "Ficção Científica",
                            Title = "A Origem",
                            Year = 2010
                        });
                });

            modelBuilder.Entity("ProducerFilm.Models.MovieListHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producers")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Studios")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Winner")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year");

                    b.ToTable("MovieListHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
