// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProducerFilm.Infrastructure.Data;

#nullable disable

namespace ProducerFilm.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ProducerFilm.Domain.Entities.MovieListHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Producers")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("Producers");

                    b.Property<string>("Studios")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Studios");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<string>("Winner")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("Winner");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_MovieListHistories_Year");

                    b.ToTable("MovieListHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
